SHELL = /bin/sh

all: 
	gcc -Wall exemple1.c -pthread -o exemple1
	gcc -Wall exemple2.c -pthread -o exemple2
	gcc -Wall exemple3.c -pthread -o exemple3
	gcc -Wall exemple5.c -pthread -o exemple5
	gcc -Wall exemple6.c -pthread -o exemple6
	gcc -Wall exemple7.c -pthread -o exemple7
	gcc -Wall exemple8.c -pthread -o exemple8

clean:
	rm -f ex1 ex2 ex3 ex5 ex6 ex7 ex8
